"""ThinkStack —— 一个「一切皆为可编写的扩展」的 Python 3 Agent 框架。

公开接口：ThinkStack, Config, Agent, AgentResult, EchoAgent, ToolCallingAgent,
MarkdownAgent, Tool, ToolResult, FunctionTool, ToolRegistry, tool, Memory,
ShortTermMemory, LongTermMemory, InMemoryLongTermMemory, JsonFileLongTermMemory,
WorkingMemory, Scheduler, SerialScheduler, ParallelScheduler, PriorityScheduler,
Task, TaskResult, Reasoner, EchoReasoner, markdown_to_html, ExpandHook, expand_hook,
register_extension, ExtensionHandle, ExtensionRegistry, ThinkStackServer, WebConsole,
以及 ThinkStackError 异常体系。
"""

from thinkstack.config import Config
from thinkstack.core import (
    Agent,
    AgentResult,
    EchoAgent,
    EchoReasoner,
    EmptyInput,
    FunctionTool,
    InMemoryLongTermMemory,
    JsonFileLongTermMemory,
    LongTermMemory,
    MarkdownAgent,
    Memory,
    ParallelScheduler,
    PriorityScheduler,
    Reasoner,
    Scheduler,
    SerialScheduler,
    ShortTermMemory,
    Task,
    TaskResult,
    ThinkStack,
    Tool,
    ToolCallingAgent,
    ToolRegistry,
    ToolResult,
    WorkingMemory,
    iter_agent_loop,
    markdown_to_html,
    run_agent_loop,
    tool,
)
from thinkstack.errors import (
    AgentError,
    ConfigError,
    ExtensionAccessError,
    ExtensionLoadError,
    ExtensionValidationError,
    MemoryError,
    SchedulerError,
    ThinkStackError,
    ToolError,
)
from thinkstack.expand import (
    ExpandHook,
    ExtensionHandle,
    ExtensionLoader,
    ExtensionRegistry,
    expand_hook,
    register_extension,
)
from thinkstack.runtime import ThinkStackServer, WebConsole

__version__ = "1.1.0"

__all__ = [
    "ThinkStack",
    "Config",
    "Agent",
    "AgentResult",
    "run_agent_loop",
    "iter_agent_loop",
    "EchoAgent",
    "ToolCallingAgent",
    "MarkdownAgent",
    "Tool",
    "ToolResult",
    "FunctionTool",
    "ToolRegistry",
    "tool",
    "EmptyInput",
    "Memory",
    "ShortTermMemory",
    "LongTermMemory",
    "InMemoryLongTermMemory",
    "JsonFileLongTermMemory",
    "WorkingMemory",
    "Scheduler",
    "SerialScheduler",
    "ParallelScheduler",
    "PriorityScheduler",
    "Task",
    "TaskResult",
    "Reasoner",
    "EchoReasoner",
    "markdown_to_html",
    "ExpandHook",
    "expand_hook",
    "register_extension",
    "ExtensionHandle",
    "ExtensionRegistry",
    "ExtensionLoader",
    "ThinkStackServer",
    "WebConsole",
    "ThinkStackError",
    "ConfigError",
    "ToolError",
    "MemoryError",
    "SchedulerError",
    "AgentError",
    "ExtensionLoadError",
    "ExtensionValidationError",
    "ExtensionAccessError",
    "__version__",
]
