"""ThinkStack —— 一个「一切皆为可编写的扩展」的 Python 3 Agent 框架。

公开接口：ThinkStack, Config, Agent, AgentResult, EchoAgent, ToolCallingAgent,
MarkdownAgent, Tool, ToolResult, FunctionTool, ToolRegistry, tool, Memory,
ShortTermMemory, LongTermMemory, InMemoryLongTermMemory, JsonFileLongTermMemory,
WorkingMemory, Scheduler, SerialScheduler, ParallelScheduler, PriorityScheduler,
Task, TaskResult, Reasoner, EchoReasoner, markdown_to_html, ExpandHook, expand_hook,
register_extension, ExtensionHandle, ExtensionRegistry, ThinkStackServer,
Skill, SkillRegistry, ThinkStackError 异常体系，以及 TS 状态码
（ts_status / TSStatusError / TS_CODE_*）。
"""

from thinkstack.config import Config
from thinkstack.core import (
    Agent,
    AgentResult,
    EchoAgent,
    EchoReasoner,
    EmptyInput,
    FunctionTool,
    InMemoryLongTermMemory,
    JsonFileLongTermMemory,
    LongTermMemory,
    MarkdownAgent,
    Memory,
    ParallelScheduler,
    PriorityScheduler,
    Reasoner,
    Scheduler,
    SerialScheduler,
    ShortTermMemory,
    Skill,
    SkillRegistry,
    Task,
    TaskResult,
    ThinkStack,
    Tool,
    ToolCallingAgent,
    ToolRegistry,
    ToolResult,
    WorkingMemory,
    iter_agent_loop,
    markdown_to_html,
    run_agent_loop,
    tool,
)
from thinkstack.errors import (
    TSStatusError,
    AgentError,
    ConfigError,
    ExtensionAccessError,
    ExtensionLoadError,
    ExtensionValidationError,
    MemoryError,
    SchedulerError,
    SkillError,
    ThinkStackError,
    ToolError,
    TS_CODE_BLACKHOLE,
    TS_CODE_EXT_API_ERROR,
    TS_CODE_EXT_ERROR,
    TS_CODE_KEY_ERROR,
    TS_CODE_LLM_TOKEN_EXHAUSTED,
    TS_CODE_MODEL_404,
    TS_CODE_OK,
    TS_CODE_TS_ERROR,
    TS_CODE_TS_LOST,
    TS_CODE_UNKNOWN,
    TS_CODE_URL_404,
    TS_CODE_MESSAGES,
    ts_status,
)
from thinkstack.expand import (
    ExpandHook,
    ExtensionHandle,
    ExtensionLoader,
    ExtensionRegistry,
    expand_hook,
    register_extension,
)
from thinkstack.runtime import ThinkStackServer

__version__ = "1.3.0"

__all__ = [
    "ThinkStack",
    "Config",
    "Agent",
    "AgentResult",
    "run_agent_loop",
    "iter_agent_loop",
    "EchoAgent",
    "ToolCallingAgent",
    "MarkdownAgent",
    "Tool",
    "ToolResult",
    "FunctionTool",
    "ToolRegistry",
    "tool",
    "EmptyInput",
    "Memory",
    "ShortTermMemory",
    "LongTermMemory",
    "InMemoryLongTermMemory",
    "JsonFileLongTermMemory",
    "WorkingMemory",
    "Scheduler",
    "SerialScheduler",
    "ParallelScheduler",
    "PriorityScheduler",
    "Task",
    "TaskResult",
    "Reasoner",
    "EchoReasoner",
    "markdown_to_html",
    "ExpandHook",
    "expand_hook",
    "register_extension",
    "ExtensionHandle",
    "ExtensionRegistry",
    "ExtensionLoader",
    "Skill",
    "SkillRegistry",
    "ThinkStackServer",
    "ThinkStackError",
    "ConfigError",
    "ToolError",
    "MemoryError",
    "SchedulerError",
    "AgentError",
    "ExtensionLoadError",
    "ExtensionValidationError",
    "ExtensionAccessError",
    "SkillError",
    "TSStatusError",
    "ts_status",
    "TS_CODE_OK",
    "TS_CODE_EXT_API_ERROR",
    "TS_CODE_EXT_ERROR",
    "TS_CODE_LLM_TOKEN_EXHAUSTED",
    "TS_CODE_URL_404",
    "TS_CODE_MODEL_404",
    "TS_CODE_KEY_ERROR",
    "TS_CODE_TS_ERROR",
    "TS_CODE_TS_LOST",
    "TS_CODE_BLACKHOLE",
    "TS_CODE_UNKNOWN",
    "TS_CODE_MESSAGES",
    "__version__",
]
